name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的主分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # 或者你的项目需要的 Node.js 版本

      - name: Install dependencies
        working-directory: ./llm-vram-calc-web
        run: yarn install

      - name: Build project
        working-directory: ./llm-vram-calc-web
        run: CI=false yarn build

      - name: Create docs directory
        run: mkdir -p ./docs

      - name: Copy build to docs
        run: cp -r ./llm-vram-calc-web/build/. ./docs/

      - name: Clean up previous worktree (if any)
        run: |
          if [ -d github-pages-deploy-action-temp-deployment-folder ]; then
            sudo rm -rf github-pages-deploy-action-temp-deployment-folder
          fi

      - name: Update Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs #指定 docs 的文件夹
          branch: gh-pages  # 部署到 gh-pages 分支，如果直接使用 docs 目录可删除此行
