name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./llm-vram-calc-web
        run: yarn install

      - name: Build project
        working-directory: ./llm-vram-calc-web
        run: CI=false yarn build

      - name: Create docs directory
        run: mkdir -p ./docs

      - name: Copy build to docs
        run: cp -r ./llm-vram-calc-web/build/. ./docs/

      - name: Fix Git installation
        run: |
          sudo apt-get update
          sudo apt-get remove -y git
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
